### ISSUE TITLE
A working 4K monitor version

### ISSUE THREAD

**Issue by locmai0808** [rbrasga/TLFishingBot#9]
Thank to the original author @rbrasga, I was able to modify and got a 4k version to work. (won't work on 1440p yet)
The stamina image is now just the bottom of the stamina bar, so it will look at the bottom and see if it drains out.
The fishbar image is now slightly bigger, so that when it shines, it can still look for the fishbar.

https://github.com/locmai0808/throne-and-liberty-fishing-bot

**Comment by atitdRhaom** [comment]
Which tier of HUD UI Size are you using in the Edit Hud option?

**Comment by VinderOrnitier** [comment]
> Edit: deleted as I think this is not a fair play lol

Hi, can I ask you make an exception and give me your version? I will try to adapt it for my 1440p

**Comment by locmai0808** [comment]
> 
> 
> > Edit: deleted as I think this is not a fair play lol
> 
> 
> 
> Hi, can I ask you make an exception and give me your version? I will try to adapt it for my 1440p
> 
> 

I already implemented for 1440p, and it automatically detect 1440p or 4k. But you can pretty much follow my comment above to improve the script in this repo.

2 things:
Only have to look at the bottom of the stamina bar to determine whether we need stamina
Fish bar should be more than just 1px height, and should be longer so that it can be detected precisely when it shines.

The rest are the pretty much the same.
Though you will need to config the image regions more precisely too, as each of us uses different hud size.

**Comment by VinderOrnitier** [comment]
> 2 things:
> Only have to look at the bottom of the stamina bar to determine whether we need stamina
> Fish bar should be more than just 1px height, and should be longer so that it can be detected precisely when it shines.

Thanks for the reply, will try do as you described

**Comment by N4Z1T** [comment]
> Thank to the original author @rbrasga, I was able to modify and got a 4k version to work. (won't work on 1440p yet) The stamina image is now just the bottom of the stamina bar, so it will look at the bottom and see if it drains out. The fishbar image is now slightly bigger, so that when it shines, it can still look for the fishbar.
> 
> ~https://github.com/locmai0808/throne-and-liberty-fishing-bot~
> 
> Edit: deleted as I think this is not a fair play lol

is there way to verify the correct region in-game? this drive me crazy no matter what XY i put it still not work lol. keep spamming failQ/R

**Comment by locmai0808** [comment]
@N4Z1T 

To test cordinates:

```python
import cv2
import os

def check_images_in_screenshot(screenshot_path, template_paths, confidence=0.7):
    # Load the main screenshot
    screenshot = cv2.imread(screenshot_path)
    if screenshot is None:
        print(f"Error: Unable to load screenshot '{screenshot_path}'")
        return

    # Dictionary to store detection results
    results = {}

    for template_path in template_paths:
        # Load each template image
        template = cv2.imread(template_path)
        if template is None:
            print(f"Error: Unable to load template '{template_path}'")
            continue

        # Convert both images to grayscale for template matching
        screenshot_gray = cv2.cvtColor(screenshot, cv2.COLOR_BGR2GRAY)
        template_gray = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)

        # Template matching
        result = cv2.matchTemplate(screenshot_gray, template_gray, cv2.TM_CCOEFF_NORMED)
        _, max_val, _, max_loc = cv2.minMaxLoc(result)

        # Check if the highest match value meets the confidence threshold
        if max_val >= confidence:
            results[template_path] = {
                "found": True,
                "location": max_loc,
                "confidence": max_val
            }
            print(f"Found '{template_path}' in '{screenshot_path}' at location {max_loc} with confidence {max_val:.2f}")
        else:
            results[template_path] = {
                "found": False,
                "confidence": max_val
            }
            print(f"'{template_path}' not found in '{screenshot_path}' (confidence: {max_val:.2f})")

    return results


base_dir = os.path.dirname(__file__)  # Directory where this script is located
screenshot_path = os.path.join(base_dir, "1.png")
template_dir = os.path.join(base_dir, "assets")
TEST_IMAGE_POST_FIX = "_1440"  # Change to "" for 2160p

template_paths = [
    os.path.join(template_dir, f"q{TEST_IMAGE_POST_FIX}.png"),
    os.path.join(template_dir, f"f{TEST_IMAGE_POST_FIX}.png"),
    os.path.join(template_dir, f"f{TEST_IMAGE_POST_FIX}.png"),
    os.path.join(template_dir, f"fishbar{TEST_IMAGE_POST_FIX}.png"),
    os.path.join(template_dir, f"stamina{TEST_IMAGE_POST_FIX}.png")
]

results = check_images_in_screenshot(screenshot_path, template_paths)
```

You need to crop your own `q.png`, `f.png`, `fishbar.png` and `stamina.png`

Then run the script to find the starting X, Y

**Comment by N4Z1T** [comment]
Could you please clarify if I need to crop the entire fishbar and stamina
bar, or just the smaller sections as shown in the ‘imgs’ directory? I’ve
tried both methods, but the image is still not being detected. Also, I’m
using a 1080p resolution.  I truly appreciate your patience and assistance.”

**Comment by locmai0808** [comment]
@N4Z1T the script above will work for any screen resolution.
As long as you crop those images from your own screenshot.

`q.png` should be the square button with letter Q in it. 
`f.png` should be the square button with letter F in it
`firstbar.png` should look kinda like `>-------`, while the whole fishbar looks like `<fish>-------` - so you just want this part `>-------`
`stamina.png` should be only the bottom of the stamina bar, you dont need to look at the whole bar to detect whether you need stamina.

Also if you look at the script ,it's looking at `assets` directory instead of `imgs`....so change that if your images are in `imgs`

**Comment by N4Z1T** [comment]
If you don't mind, could you please take a look at the image I have attached, both before and after cropping? I am still unable to achieve the correct image.

before
![isux](https://github.com/user-attachments/assets/afc4dc4c-aefc-43af-905f-0a196aaa06cd)
![isux2](https://github.com/user-attachments/assets/90cbbe40-27c9-460c-a3f8-ac7fe789f7f2)

after
![fishbar3](https://github.com/user-attachments/assets/6012b2ac-b429-4161-a4c2-dcb78815b966)
![stamina](https://github.com/user-attachments/assets/ba6c1dae-f4e5-4c64-9641-141c754e6bb4)

**Comment by locmai0808** [comment]
@N4Z1T 

4k:
![stamina](https://github.com/user-attachments/assets/1eeacfef-4574-4ca5-94e9-89ae32dba200)
![f](https://github.com/user-attachments/assets/1e0fee31-6c14-4c8d-9ee3-652f3355a9b1)
![fishbar](https://github.com/user-attachments/assets/d21bdc4f-5fd3-4d14-8c80-6fe7f50ad21f)
![q](https://github.com/user-attachments/assets/875e4817-3051-45f9-bff3-38de78ab7d46)

1440p:
![stamina_1440](https://github.com/user-attachments/assets/1f46c20f-0c54-460d-9ec6-1608658a61ad)
![f_1440](https://github.com/user-attachments/assets/c81dbfa2-f3bc-4f68-8771-ea100e48be9f)
![fishbar_1440](https://github.com/user-attachments/assets/e07aeed1-0cdb-43fa-8a6c-3310f8e4008e)
![q_1440](https://github.com/user-attachments/assets/3019744e-10a4-407d-91eb-76cf7e2b823a)

**Comment by N4Z1T** [comment]
Your script functions effectively and performs the tasks exceptionally well! However, it seems unable to detect the fish bar and stamina from the image I cropped. Perhaps my cropping skills could use some improvement. 😊

**Comment by Pinwir** [comment]
> Thank to the original author @rbrasga, I was able to modify and got a 4k version to work. (won't work on 1440p yet) The stamina image is now just the bottom of the stamina bar, so it will look at the bottom and see if it drains out. The fishbar image is now slightly bigger, so that when it shines, it can still look for the fishbar.
> 
> ~https://github.com/locmai0808/throne-and-liberty-fishing-bot~
> 
> Edit: deleted as I think this is not a fair play lol

Hi, I have a question. It worked perfectly for me at 1440p, but I can't get it to detect the stamina bar properly in 4K. How did you get it to work correctly in 4K? I already adjusted the location and took a picture of the bar, but it either uses up a bit of stamina and then reloads, or it uses it all and doesn’t reload. Could you show me an example of how you set it up?

**Comment by locmai0808** [comment]
> > Thank to the original author @rbrasga, I was able to modify and got a 4k version to work. (won't work on 1440p yet) The stamina image is now just the bottom of the stamina bar, so it will look at the bottom and see if it drains out. The fishbar image is now slightly bigger, so that when it shines, it can still look for the fishbar.
> 
> > 
> 
> > ~https://github.com/locmai0808/throne-and-liberty-fishing-bot~
> 
> > 
> 
> > Edit: deleted as I think this is not a fair play lol
> 
> 
> 
> Hi, I have a question. It worked perfectly for me at 1440p, but I can't get it to detect the stamina bar properly in 4K. How did you get it to work correctly in 4K? I already adjusted the location and took a picture of the bar, but it either uses up a bit of stamina and then reloads, or it uses it all and doesn’t reload. Could you show me an example of how you set it up?

Can you show me the picture of your stamina bar? Also are you using low confidence? May have to up the confidence to 90% or higher.

**Comment by Pinwir** [comment]
> > > Thank to the original author @rbrasga, I was able to modify and got a 4k version to work. (won't work on 1440p yet) The stamina image is now just the bottom of the stamina bar, so it will look at the bottom and see if it drains out. The fishbar image is now slightly bigger, so that when it shines, it can still look for the fishbar.
> > 
> > 
> > > 
> > 
> > 
> > > ~https://github.com/locmai0808/throne-and-liberty-fishing-bot~
> > 
> > 
> > > 
> > 
> > 
> > > Edit: deleted as I think this is not a fair play lol
> > 
> > 
> > Hi, I have a question. It worked perfectly for me at 1440p, but I can't get it to detect the stamina bar properly in 4K. How did you get it to work correctly in 4K? I already adjusted the location and took a picture of the bar, but it either uses up a bit of stamina and then reloads, or it uses it all and doesn’t reload. Could you show me an example of how you set it up?
> 
> Can you show me the picture of your stamina bar? Also are you using low confidence? May have to up the confidence to 90% or higher.

Sure, I'll share the image I'm using for this and the data provided by the script you shared earlier:

Script

'q.png' at location (1887, 1380) with confidence 1.00
'f.png' at location (2315, 1276) with confidence 0.99
'stamina.png' at location (2235, 1401) with confidence 1.00
'fishbar.png' at location (2189, 1180) with confidence 1.00


https://i.imgur.com/IWMo5hc.jpeg
![q](https://github.com/user-attachments/assets/c2f4951c-0192-490a-9bd5-d893ee7a3bc6)
![f](https://github.com/user-attachments/assets/64b7f3eb-6bf7-47a5-87d5-8db7267c18f4)
![stamina](https://github.com/user-attachments/assets/bd4b3b3f-9c72-4104-8358-08803a6aadc3)
![fishbar](https://github.com/user-attachments/assets/fa934720-cc88-4439-9376-63cfe7fbf07c)

I'll also leave how I have the configuration of the .py file.


 

class FishBot:

    #TLWINDOW="TL 1.138.22.570"
    def __init__(self):
        # Selecting the "Q Snap up with"
        self.snapRegion = {"mon": 1, "top": (1380), "left": (1887), "width": (45), "height": (45)}

         # Selecting the "F Cast float"
        self.castRegion = {"mon": 1, "top": (1276), "left": (2315), "width": (45), "height": (45)}

         # Selecting the "F Cast float"
        self.recoverRegion = {"mon": 1, "top": (1276), "left": (2315), "width": (45), "height": (45)}

         # Selecting the "Capture Bar"
        self.fishRegion = {"mon": 1, "top": (1180), "left": (2189), "width": (29), "height": (4)}

         # Selecting the "Fishing Pole Stamina Bar"
        self.staminaRegion = {"mon": 1, "top": (1401), "left": (2235), "width": (12), "height": (7)}

        # Starting screenshotting object
        self.sct = mss.mss()

    def screenGrab(self, region):
        IMG = None
        while IMG == None:
            try:
                IMG = self.sct.grab(region)
            except Exception as e:
                print(e)
                print(f"[Error] Unable to take screenshot. {region}")
                time.sleep(0.1)
        return IMG

    def getFishBar(self):
        #RGB 255,255,224 (+-10)
        # X Range: 782-924
        # Along Y Axis 1455

        # (left, top, width, height)
        fishbarImg = self.screenGrab(self.fishRegion)
        fishbarImg = np.array(fishbarImg)
        foundFish = None
        try:
            foundFish = pyautogui.locate("imgs/fishbar3.png", fishbarImg, grayscale=True, confidence=.9)
        except Exception as ImageNotFoundException:
            print("foundFish failed")
        if foundFish == None: return None
        _, top, _, _ = foundFish
        return top
    
    def needStamina(self):
        staminaImg = self.screenGrab(self.staminaRegion)
        staminaImg = np.array(staminaImg)
        foundStam = None
        try:
            foundStam = pyautogui.locate("imgs/stamina.png", staminaImg, grayscale=True, confidence=.9)
        except Exception as ImageNotFoundException:
            print("foundStam failed")
        return foundStam == None
    
    def main(self):

        # Select Application Window
        throneWindows = pyautogui.getWindowsWithTitle("TL 1")
        throneWindow = None
        for window in throneWindows:
            if "TL 1" in window.title:
                throneWindow = window
                break
        cv2.namedWindow("visuals", cv2.WINDOW_NORMAL)
        throneWindow.activate()
        
        q_count = 0
        wasCast = False
        CASTED = time.time()
        tracker = 0
        while True:
            # Sleep for 0.1 - 0.2s
            animationSleepTime = .1 + (.1 * random.random())
            if wasCast and time.time() - CASTED > 60:
                wasCast = False
                
            # Screenshot
            snapImg = self.screenGrab(self.snapRegion)
            snapImg = np.array(snapImg)

            castImg = self.screenGrab(self.castRegion)
            castImg = np.array(castImg)

            # Looking for the Q
            foundQ = None
            try:
                foundQ = pyautogui.locate("imgs/Q2.png", snapImg, grayscale=True, confidence=.9)
            except Exception as ImageNotFoundException:
                print("foundQ failed")
            if foundQ:
                # Pressing Q
                pyautogui.keyDown('q')
                pyautogui.keyUp('q')
                q_count += 1
                print(f"Pressing Q (Snap up with) {q_count}")
                ActiveKey = "d"
                pyautogui.keyDown(ActiveKey)
                
                # Progress Tracker
                track_progress = []
                # Continue down this chain until the fish is caught
                #don't break out of fishing loop until at least 30 seconds after "caught"
                START = time.time()
                while True:
                    # Fishing attempt failed
                    if time.time() - START > 5:
                        recoverImg = self.screenGrab(self.recoverRegion)
                        recoverImg = np.array(recoverImg)
                        foundF = None
                        try:
                            foundF = pyautogui.locate("imgs/F2.png", recoverImg, grayscale=True, confidence=.9)
                        except Exception as ImageNotFoundException:
                            print("foundF failed")
                        if foundF == None:
                            # Screenshot
                            if SCREENSHOT_CATCH:
                                monitor = self.sct.monitors[1]
                                catchImg = self.sct.grab(monitor)
                                mss.tools.to_png(catchImg.rgb, catchImg.size, output=f"fish_caught_{q_count}.png")
                            print("Reeling in completed...")
                            tracker = 0
                            break
                    top = self.getFishBar()
                    if top == None: continue
                    # Measure progress until progress since last check is 0.
                    if len(track_progress) == 0:
                        #Add the current offset
                        track_progress.append(top)
                        continue
                    track_progress.append(top)
                    progress = track_progress[-1] - track_progress [-2]
                    if progress <= 0:
                        track_progress = []
                        pyautogui.keyUp(ActiveKey)
                        if ActiveKey == "d":
                            ActiveKey = "a"
                        else:
                            ActiveKey = "d"
                        pyautogui.keyDown(ActiveKey)
                    
                    # Let stamina recover if it is low
                    if self.needStamina():
                        pyautogui.keyUp(ActiveKey)
                        time.sleep(.3 + animationSleepTime)
                        pyautogui.keyDown(ActiveKey)
                    time.sleep(animationSleepTime)
                    #pyautogui.keyUp(ActiveKey)
                    
                pyautogui.keyUp(ActiveKey)
                time.sleep(5)
                wasCast = False
                continue

            foundF = None
            try:
                foundF = pyautogui.locate("imgs/F.png", castImg, grayscale=True, confidence=.9)
            except Exception as ImageNotFoundException:
                print("foundF failed")
            # Looking for the F
            if not wasCast and foundF:
                pyautogui.keyDown('f')
                pyautogui.keyUp('f')
                print("F Cast float")
                tracker += 1
                time.sleep(2 + animationSleepTime)
                wasCast = True
                CASTED = time.time()
                
            if tracker >= 5: sys.exit()
                
            time.sleep(0.125)

**Comment by Pinwir** [comment]
've managed to get the stamina bar detection to work, now I just need it to detect the fishing bar. It works initially, but after 5 seconds it stops, and it seems like it's not detecting the fishing bar.

**Comment by locmai0808** [comment]
> foundFish = pyautogui.locate("imgs/fishbar3.png", fishbarImg, grayscale=True, confidence=.9)

this is too much, try 0.7

**Comment by Pinwir** [comment]
> > foundFish = pyautogui.locate("imgs/fishbar3.png", fishbarImg, grayscale=True, confidence=.9)
> 
> this is too much, try 0.7
> 
> `self.fishRegion = {"mon": 1, "top": (1180), "left": (2189), "width": (29), "height": (4)}`
> 
> height is wrong, must be about the same height as the fish bar

I already made the changes you recommended, but it still doesn't detect correctly. It seems to work up to a certain point and stops moving after about 5 seconds. I tried changing several things. I'll leave you a picture and the updated parameters.

![Sin título](https://github.com/user-attachments/assets/0291413b-94f8-4fb7-bca0-29642cd6bf2b)



	#TLWINDOW="TL 1.138.22.570"
	def __init__(self):
		# Selecting the "Q Snap up with"
		self.snapRegion = {"mon": 1, "top": (1345), "left": (1889), "width": (33), "height": (33)}

		 # Selecting the "F Cast float"
		self.castRegion = {"mon": 1, "top": (1253), "left": (2268), "width": (33), "height": (33)}

		 # Selecting the "F Cast float"
		self.recoverRegion = {"mon": 1, "top": (805), "left": (1525), "width": (33), "height": (33)}

		 # Selecting the "Capture Bar"
		self.fishRegion = {"mon": 1, "top": (1168), "left": (2156), "width": (25), "height": (230)}

		 # Selecting the "Fishing Pole Stamina Bar"
		self.staminaRegion = {"mon": 1, "top": (1360), "left": (2197), "width": (12), "height": (138)}

		# Starting screenshotting object
		self.sct = mss.mss()

	def screenGrab(self, region):
		IMG = None
		while IMG == None:
			try:
				IMG = self.sct.grab(region)
			except Exception as e:
				print(e)
				print(f"[Error] Unable to take screenshot. {region}")
				time.sleep(0.1)
		return IMG

	def getFishBar(self):
		#RGB 255,255,224 (+-10)
		# X Range: 782-924
		# Along Y Axis 1455

		# (left, top, width, height)
		fishbarImg = self.screenGrab(self.fishRegion)
		fishbarImg = np.array(fishbarImg)
		foundFish = None
		try:
			foundFish = pyautogui.locate("imgs/fishbar3.png", fishbarImg, grayscale=True, confidence=.7)
		except Exception as ImageNotFoundException:
			print("foundFish failed")
		if foundFish == None: return None
		_, top, _, _ = foundFish
		return top
	
	def needStamina(self):
		staminaImg = self.screenGrab(self.staminaRegion)
		staminaImg = np.array(staminaImg)
		foundStam = None
		try:
			foundStam = pyautogui.locate("imgs/stamina.png", staminaImg, grayscale=True, confidence=.9)
		except Exception as ImageNotFoundException:
			print("foundStam failed")
		return foundStam == None
	
	def main(self):


		# Select Application Window
		throneWindows = pyautogui.getWindowsWithTitle("TL 1")
		throneWindow = None
		for window in throneWindows:
			if "TL 1" in window.title:
				throneWindow = window
				break
		cv2.namedWindow("visuals", cv2.WINDOW_NORMAL)
		throneWindow.activate()
		
		q_count = 0
		wasCast = False
		CASTED = time.time()
		tracker = 0
		while True:
			# Sleep for 0.1 - 0.2s
			animationSleepTime = .1 + (.1 * random.random())
			if wasCast and time.time() - CASTED > 60:
				wasCast = False
				
			# Screenshot
			snapImg = self.screenGrab(self.snapRegion)
			snapImg = np.array(snapImg)

			castImg = self.screenGrab(self.castRegion)
			castImg = np.array(castImg)

			# Looking for the Q
			foundQ = None
			try:
				foundQ = pyautogui.locate("imgs/Q2.png", snapImg, grayscale=True, confidence=.9)
			except Exception as ImageNotFoundException:
				print("foundQ failed")
			if foundQ:
				# Pressing Q
				pyautogui.keyDown('q')
				pyautogui.keyUp('q')
				q_count += 1
				print(f"Pressing Q (Snap up with) {q_count}")
				ActiveKey = "d"
				pyautogui.keyDown(ActiveKey)
				
				# Progress Tracker
				track_progress = []
				# Continue down this chain until the fish is caught
				#don't break out of fishing loop until at least 30 seconds after "caught"
				START = time.time()
				while True:
					# Fishing attempt failed
					if time.time() - START > 5:
						recoverImg = self.screenGrab(self.recoverRegion)
						recoverImg = np.array(recoverImg)
						foundF = None
						try:
							foundF = pyautogui.locate("imgs/F2.png", recoverImg, grayscale=True, confidence=.9)
						except Exception as ImageNotFoundException:
							print("foundF failed")
						if foundF == None:
							# Screenshot
							if SCREENSHOT_CATCH:
								monitor = self.sct.monitors[1]
								catchImg = self.sct.grab(monitor)
								mss.tools.to_png(catchImg.rgb, catchImg.size, output=f"fish_caught_{q_count}.png")
							print("Reeling in completed...")
							tracker = 0
							break
					top = self.getFishBar()
					if top == None: continue
					# Measure progress until progress since last check is 0.
					if len(track_progress) == 0:
						#Add the current offset
						track_progress.append(top)
						continue
					track_progress.append(top)
					progress = track_progress[-1] - track_progress [-2]
					if progress <= 0:
						track_progress = []
						pyautogui.keyUp(ActiveKey)
						if ActiveKey == "d":
							ActiveKey = "a"
						else:
							ActiveKey = "d"
						pyautogui.keyDown(ActiveKey)
					
					# Let stamina recover if it is low
					if self.needStamina():
						pyautogui.keyUp(ActiveKey)
						time.sleep(.3 + animationSleepTime)
						pyautogui.keyDown(ActiveKey)
					time.sleep(animationSleepTime)
					#pyautogui.keyUp(ActiveKey)
					
				pyautogui.keyUp(ActiveKey)
				time.sleep(5)
				wasCast = False
				continue

			foundF = None
			try:
				foundF = pyautogui.locate("imgs/F.png", castImg, grayscale=True, confidence=.9)
			except Exception as ImageNotFoundException:
				print("foundF failed")
			# Looking for the F
			if not wasCast and foundF:
				pyautogui.keyDown('f')
				pyautogui.keyUp('f')
				print("F Cast float")
				tracker += 1
				time.sleep(2 + animationSleepTime)
				wasCast = True
				CASTED = time.time()
				
			if tracker >= 5: sys.exit()
				
			time.sleep(0.125)

**Comment by locmai0808** [comment]
@Pinwir your original fishbar was corrrect, it was the `self.fishRegion`'s height that is not correct. It is supposed to be the fishbar's total height

**Comment by Pinwir** [comment]
@locmai0808 I made the changes to get the total height (H) of the fishing bar, but I’m still having the same problem. Or maybe I’m misunderstanding something. I’m leaving the code line and the images it takes because I really don’t understand much anymore. If possible, could you provide an example in an image or something in case I’m misunderstanding? Thanks

![fishbar_debug_0](https://github.com/user-attachments/assets/26d3fc7c-31b2-4df0-8b47-f9cf0bafb4c6)
![fishbar_debug_10](https://github.com/user-attachments/assets/e9900af7-ead6-426f-a68f-33ed8abf397a)
![fishbar_debug_19](https://github.com/user-attachments/assets/80ccd3bd-cb09-4286-99f6-52fff48b2d5a)
![fishbar_debug_25](https://github.com/user-attachments/assets/30e58ba2-102f-4583-a769-935936e2bb0e)

self.fishRegion = {"mon": 1, "top": (1161), "left": (2156), "width": (25), "height": (215)}

**Comment by locmai0808** [comment]
![image](https://github.com/user-attachments/assets/327d32f0-2b0a-477e-8dbe-b7c16d4adb13)

Use this instead, this was your original fish bar.

Because your fish bar's image has 29 pixels width and 4 pixels height, this is what your `self.fishRegion` should look like:

```
self.fishRegion = {"mon": 1, "top": (1161), "left": (2156), "width": (29), "height": (202)}
```

I changed to 202 because that's the height I see

**Comment by locmai0808** [comment]
Here's my configuration for HUD SIZE tier 1:

```python
REGIONS = {
    '1080': {
        'snapRegion': {"mon": 1, "left": 936, "top": 710, "width": 15, "height": 15},
        'castRegion': {"mon": 1, "left": 1183, "top": 652, "width": 14, "height": 14},
        'recoverRegion': {"mon": 1, "left": 1183, "top": 620, "width": 14, "height": 14},
        'fishRegion': {"mon": 1, "left": 1109, "top": 595, "width": 12, "height": 124},
        'staminaRegion': {"mon": 1, "left": 1134, "top": 719, "width": 8, "height": 3}
    },
    '1440': {
        'snapRegion': {"mon": 1, "left": 1259, "top": 909, "width": 18, "height": 18},
        'castRegion': {"mon": 1, "left": 1527, "top": 844, "width": 19, "height": 19},
        'recoverRegion': {"mon": 1, "left": 1527, "top": 807, "width": 19, "height": 19},
        'fishRegion': {"mon": 1, "left": 1445, "top": 782, "width": 29, "height": 145},
        'staminaRegion': {"mon": 1, "left": 1475, "top": 918, "width": 8, "height": 8}
    },
    '2160': {
        'snapRegion': {"mon": 1, "left": 1880, "top": 1347, "width": 32, "height": 32},
        'castRegion': {"mon": 1, "left": 2270, "top": 1255, "width": 30, "height": 30},
        'recoverRegion': {"mon": 1, "left": 2270, "top": 1204, "width": 30, "height": 30},
        'fishRegion': {"mon": 1, "left": 2157, "top": 1168, "width": 29, "height": 199},
        'staminaRegion': {"mon": 1, "left": 2197, "top": 1362, "width": 12, "height": 7}
    }
}
```

And here are all the assets I took for each:
| Image |  1080p | 1440p |  4k |
| :---------------- | :------: | :----: |  :----: |
| Q |  ![q_1080](https://github.com/user-attachments/assets/7347fc4d-12e1-4a6f-a31f-2f41d6083532) | ![q_1440](https://github.com/user-attachments/assets/4bcc3929-fa5d-410e-9d2b-1ec53ea90089) | ![q_2160](https://github.com/user-attachments/assets/a15c0962-9d55-4f9f-a5f6-21ca53305f20) |
| F |  ![f_1080](https://github.com/user-attachments/assets/a924be13-7ac8-4693-9962-455093755a06) | ![f_1440](https://github.com/user-attachments/assets/8f4c8451-89d1-4759-8a39-a2aa0c8a946f) | ![f_2160](https://github.com/user-attachments/assets/31c7b9d8-9fa7-4489-82f3-9cc99309fef3) |
| Fishbar | ![fishbar_1080](https://github.com/user-attachments/assets/61afd3c8-2795-4ce2-8655-8efc0d8ee45d) | ![fishbar_1440](https://github.com/user-attachments/assets/6ed58ab8-109e-4ce1-97d5-23244ccb905a) | ![fishbar_2160](https://github.com/user-attachments/assets/c607efa3-7784-45ef-8aca-8870f3051fa6) |
| Stamina | ![stamina_1080](https://github.com/user-attachments/assets/045e0ed4-949a-4230-ba53-bb7707d3768e) | ![stamina_1440](https://github.com/user-attachments/assets/108a8a35-31da-4d57-9513-e2b6f2ea23af) | ![stamina_2160](https://github.com/user-attachments/assets/2d936195-0748-4d98-a6f4-f74733ed565c) |

Now if you use HUD SIZE TIER 1, you can use the configuration above

**Comment by Pinwir** [comment]
@locmai0808 I also tried using the hub size 1 probe with your configuration and your images, but it didn’t work. It didn’t work with my images and your configuration either. I even tried changing the H value to 202, but it still didn’t work. Maybe my issue lies elsewhere; I’ll keep investigating to figure it out. Thanks for your help!

**Comment by locmai0808** [comment]
@Pinwir are you sure you're saving those 4k assets with the correct names? 
If you're using hub size 1, here's the configuration:
```
'snapRegion': {"mon": 1, "left": 1880, "top": 1347, "width": 32, "height": 32},
'castRegion': {"mon": 1, "left": 2270, "top": 1255, "width": 30, "height": 30},
'recoverRegion': {"mon": 1, "left": 2270, "top": 1204, "width": 30, "height": 30},
'fishRegion': {"mon": 1, "left": 2157, "top": 1168, "width": 29, "height": 199},
'staminaRegion': {"mon": 1, "left": 2197, "top": 1362, "width": 12, "height": 7}
```

After the last patch/update, the pixels shifted.

**Comment by Pinwir** [comment]
@locmai0808 I ran the script again, and the Q was a few pixels off. Now, I passed the part where it gets stuck doing nothing. The problem occurs when I get the error 'foundStam failed' and 'foundFish failed'. From what I can see, it seems to be an issue with the 'fishbar3.png' image. I think I’ve always had the problem with that image. I am using the same 'fishbar.png' image you sent me


 'q.png'
 - Top: 1347, Left: 1891
 - Confidence: 0.95

**Comment by N4Z1T** [comment]
Wish we could use ML YOLO for object detection

**Comment by rbrasga** [comment]
> > foundFish = pyautogui.locate("imgs/fishbar3.png", fishbarImg, grayscale=True, confidence=.9)
> 
> this is too much, try 0.7
> 
> `self.fishRegion = {"mon": 1, "top": (1180), "left": (2189), "width": (29), "height": (4)}`
> 
> height is wrong, must be about the same height as the fish bar

Thanks for your support! Sorry I missed all these comments. I should sign up for email alerts on this stuff.

Feel free to submit a pull request. Or I can add you as an author. I will keep this bug open since there's a lot of good discussion here.

**Comment by rbrasga** [comment]
> Wish we could use ML YOLO for object detection

I could pretty quickly make this flexible via:

- OCR (Object character recognition) (Q/F/etc.)
- scanning the screen for color palettes (yours/fishes stamina)
- Auto scaling to UI
- Make a simple fishbot GUI to let users set <use all bait / use only selected bait / use X amount of bait / etc.>

but the original goal was a hard-to-use prototype so thousands of people wouldn't use it.

If there's enough interest in an out-of-the-box solution, I would need to make it bullet proof in terms of anti-bot detection.

Might as well throw it in there that I'm debating writing a questionable DPS meter for throne and liberty (generally reading memory is safe, but as an enterprise software engineer every solution demands perfection). It does seem there's a large demand for this, so I'll see what I can do.
